### ISSUE TITLE
the entered text is not getting cleared after selecting an item from the dropdown

### ISSUE THREAD

**Issue by PraveenMp** [optimistex/ngx-select-ex#38] opened 2018-03-13 10:17 UTC
![image](https://user-images.githubusercontent.com/9115698/37335854-955dc872-26d5-11e8-9ad7-117161b174a9.png)
it was getting cleared in the ng2-select. 
Please let me know if you need more information on the issue. Thanks in advance.

**Comment by optimistex** [comment] 2018-03-13 10:20
![image](https://user-images.githubusercontent.com/11228640/37336057-414aaa02-26c1-11e8-9bfc-b0fb4b7d6744.png)

Duplicate of https://github.com/optimistex/ngx-select-ex/issues/30

**Closed by optimistex** 2018-03-13 10:20 UTC
