### ISSUE TITLE
Possible to select whole object instead of just returning id value?

### ISSUE THREAD

**Issue by jackiewang5566** [optimistex/ngx-select-ex#57] opened 2018-04-06 14:08 UTC
Currently I can only select the id of an object, I think it would be very helpful if I could select the whole object if I wanted to populate the object data to other places. Of course we could iterate array to find the selected object, but it would be nice if there is an option doing that out of box.

**Comment by optimistex** [comment] 2018-04-06 14:56
I think about adding some option for switch return value/object.
One time I will implement it when I will got a little free time.

**Comment by optimistex** [comment] 2018-04-06 15:08
I find out that this issue is a duplicate of the: https://github.com/optimistex/ngx-select-ex/issues/31

**Closed by optimistex** 2018-04-06 15:08 UTC
Labels: enhancement
