### ISSUE TITLE
Default Selected Items

### ISSUE THREAD

**Issue by frankbecker** [optimistex/ngx-select-ex#94] opened 2018-06-25 20:52 UTC
Is there a way of setting a default selected item?
Or items for multiple options?
I did not see this in the documentation and it's a feature I'd wish this angular module had.

**Comment by optimistex** [comment] 2018-06-25 20:53
Duplicate of: https://github.com/optimistex/ngx-select-ex/issues/93

**Closed by optimistex** 2018-06-25 20:53 UTC

**Comment by frankbecker** [comment] 2018-06-25 21:02
Thank you, it's working now, but I did realized that it only works with an array of string values and not objects.

**Comment by optimistex** [comment] 2018-06-25 21:06
Look at `optionValueField`. The option defines the real selected values that define objects from the items.
So, you need set up the `defaultValue` by values supported with `optionValueField`

**Comment by frankbecker** [comment] 2018-06-25 21:16
Ok I see it now. But the defaultValue array will be an array of desired default value fields, like below:
`  public items: Array<object> = [
    {"name": 'Amsterdam', "_id":"123"},
    {"name": 'Athens', "_id":"124"}
  ];
  public item: Array<string> = [
    "123"
  ];`

Anyways, thank you, this woks.

**Comment by saitho** [comment] 2018-06-29 11:35
I just want to add that the values inside the defaultValue array have to be of the same data type than the id. My ids are of Number type, which means the values inside the defaultValue array must also be of type Number.
