### ISSUE TITLE
Support for RxJS 6, Angular 6

### ISSUE THREAD

**Issue by Miced** [optimistex/ngx-select-ex#72] opened 2018-05-09 09:36 UTC
Currently it is not possible to use this with Angular 6 since the rxjs operators follow the old 'rxjs/add/operator/' syntax. It has been deprecated and in RxJS 6 it is now removed, making the migration impossible.

Any chance to update imports? This should be trivial, but might drop some Angular 4 support.

**Comment by optimistex** [comment] 2018-05-25 08:01
Addon from the user @ChandraTerli 
https://github.com/optimistex/ngx-select-ex/issues/6#issuecomment-391364177
And below on the topic...

**Comment by Miced** [comment] 2018-05-25 08:40
I bypassed this issue using [rxjs-compat](https://github.com/ReactiveX/rxjs/tree/master/compat) for now, which is supposed to provide migration until RxJS 7.

**Comment by optimistex** [comment] 2018-05-25 08:45
Cool. You are have the solution and I have more time to put this enhance in my schedule.

**Comment by rlefever68** [comment] 2018-05-30 22:52
rxjs-compat is not working for me, unfortunately. I get " Fatal Error this.subjExternalValue.map is not a function".. using rxjs-compat 6.2.0

**Comment by scotteby** [comment] 2018-05-31 20:56
I get the same error as @rlefever68, but only when I run in production mode. 

In dev mode, I don't get any errors with rxjs-compat 6.2.0

**Comment by optimistex** [comment] 2018-06-20 03:11
Today I upgraded my general project and I don't note any issues between the ngx-select-ex and Angular 6.
Now I have installed `"rxjs-compat": "^6.2.1"`.

Looks like the issue is not actual. Closed.
_________
If it is still actual let me know how to reproduce it.

**Comment by Miced** [comment] 2018-06-20 12:14
The issue is still valid. I have v3.5.9 installed and the imports do not comply with rxjs v6.

rxjs-compat is supposed to be a stepping stone before completely moving to rxjs v6, and it will not work on rxjs v7. You can check more details about the migration here: https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/v6/migration.md

If needed I can issue a PR with the required changes.

**Comment by scotteby** [comment] 2018-06-20 12:41
Did you try running in production mode? I still get errors as of yesterday
in production mode.

**Comment by optimistex** [comment] 2018-06-20 12:45
I build so `ng build` and already use in production.
All it is ok.

But. The component is still on Angular 5. Little late I'll upgrade it for Angular 6.

Currently, I do not see the issue.

**Comment by Miced** [comment] 2018-06-20 13:33
For a quick adjustment (although this is an easy transition) you can list rxjs-compat in the `dependencies` list of the module in `package.json`, so that it is installed.

**Comment by scotteby** [comment] 2018-06-21 13:18
@optimistex , I'm using webpack, not ngbuild, and webpack in production mode gives me the error I mentioned earlier. I created a test project using ng build and noticed I don't see the errors.

I will track down the exact webpack configuration issue causing this, but we will still need a code change so that we can eventually remove the rxjs-compat library and have proper rxjs 6 support. Thanks for testing it.

**Comment by scotteby** [comment] 2018-06-21 15:14
Just in case anyone is trying to get this working with Webpack 4, you need to disable the sideEffects optimization in production mode.

` optimization: {
            sideEffects: false
}`

**Comment by galvakojis** [comment] 2018-07-10 14:29
```
ERROR in node_modules/ngx-select-ex/ngx-select/ngx-select.component.d.ts(4,10): error TS2305: Module '"/frontend/bullseye/node_modules/rxjs/BehaviorSubject"' has no exported member 'BehaviorSubject'.
frontend_1    | node_modules/rxjs/BehaviorSubject.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/BehaviorSubject'.
```
Maybe any ideas, how to resolve it?

**Comment by pktron** [comment] 2018-07-31 00:53
rxjs compatibility worked for me...
npm install --save rxjs-compat

But is gonna be deprecated on rxjs 7...

**Comment by Redlobster74** [comment] 2018-09-06 13:58
@optimistex the solution from @galvakojis fixes the compilation issue when rxjs-compat isn't used.
To be more precise I would change that line into:

`import {BehaviorSubject} from "rxjs/index";`

Is there any chance you can push this small update so everybody can start use your library without rxjs-compat?

**Comment by prikryl** [comment] 2018-09-18 08:34
@ravenwill 
downgrade compat library. It seems to be broken
```
    "rxjs": "^6.3.2",
    "rxjs-compat": "6.2.2",
```

**Comment by Disane87** [comment] 2018-09-18 15:18
> @ravenwill
> downgrade compat library. It seems to be broken
> 
> ```
>     "rxjs": "^6.3.2",
>     "rxjs-compat": "6.2.2",
> ```

This solved our problems with the error `ERROR TypeError: rxjs_Observable__WEBPACK_IMPORTED_MODULE_5__.Observable.from is not a function
at MergeMapSubscriber.project (ngx-select-ex.es5.js:250)` too

**Comment by DanniB** [comment] 2018-09-18 17:31
Please fix this. I want to get rid of rxjs-compat. Otherwise, I'm forced to switch to ng-select:

https://github.com/ng-select/ng-select

**Comment by Stan92** [comment] 2018-09-24 06:15
```

  "rxjs": "^6.3.2",
  "rxjs-compat": "6.2.2",
```

Doesn't work for me.

**Comment by sabariU** [comment] 2018-09-27 02:27
> @ravenwill
> downgrade compat library. It seems to be broken
> 
> ```
>     "rxjs": "^6.3.2",
>     "rxjs-compat": "6.2.2",
> ```

It works for me. Thanks

**Comment by prikryl** [comment] 2018-10-30 16:44
I have tried to create pull request (I don't known if it is correct to use fork and pull request). https://github.com/valor-software/ng2-select/pull/971
Could you check it? I fixed imports and switchted to pipes om few lines and package.jsom. Could you check it?
Thank you

**Comment by optimistex** [comment] 2018-10-30 18:38
@prikryl Fixed in the development version. Soon will be in a release...
Try it: `npm i ngx-select-ex@dev`

**Closed by optimistex** 2018-10-30 18:38 UTC
Labels: enhancement, important
